#!/usr/bin/perl -w

use strict;
use warnings;
use feature qw( switch );
use Data::Dumper;
use Term::ANSIColor;
use Getopt::Long qw( :config no_ignore_case bundling );

use lib "/usr/lib/smoothwall";
use header qw( :standard );

my ($help,$verbose);
$verbose = 0;
GetOptions(
	'h|help'		=>	\$help,
	'v|verbose+'	=>	\$verbose,
);

if ($help) { &usage(); }

my %redipmodsettings;

# check how we were called
given ($0) {
	when (/\.\/install/) {
		# install the mod
		print colored("We want to install the mod! \n", "bold green");
		print colored("First we need to install some perl modules.\n", "bold green");
		print colored("You will be prompted by the CPAN perl module.  It should be safe to accept all of the defaults.\n", "bold green");
		system("cpan App::cpanminus");
		system("cpan install CPAN");
		system("cpanm MIME::Lite");
		&readhash("settings", \%redipmodsettings);
		open IN, "</var/smoothwall/red/local-ipaddress" or die colored("There was a problem reading the RED IP settings: $!", "bold red");
		$redipmodsettings{'old_ip'} = readline(IN);
		chomp($redipmodsettings{'old_ip'});
		close IN or die colored("There was a problem closing the RED IP settings file after reading: $!", "bold red");
		&writehash("settings", \%redipmodsettings);
	}
	when (/\.\/uninstall/) {
		# remove the mod
		#     Make a backup/tarball and stick it in /tmp or something
		#     don't completely remove it.  Leave that as an exercise 
		#     for the user.
		print colored("Are you sure you want to remove this mod? \n", "bold yellow");
	}
	default {
		# we shoudl never get here
		print colored("We should never actually get here.  \n", "bold red");
	}
}

###############################################################################
# Subs
###############################################################################
sub usage {

	print <<END;

Usage: $0 [-h|--help] [-v|--verbose]

Options:
-h|--help			Displays this useful message.
-v|--verbose		Displays extra output.

END
	exit 0;
}
